### ISSUE TITLE
Collision type property should be trigger instead of kinematic?

### ISSUE THREAD

**Issue by nevinbaiju** [defold/tutorial-war-battles#3]
As described in the [official documentation](https://defold.com/manuals/physics/),  since we are only detecting the collision and coding out the response. It is suggested that for cases like this it is better to use collision type property as trigger instead of kinematic **as trigger is more computationally simpler.**

**Comment by britzl** [comment]
Yes, in the case of this tutorial triggers would be better since we don't care about penetration distance or direction. If we needed some kind of knock-back explosion then it would still make sense to use kinematic objects.

**Comment by nevinbaiju** [comment]
Yes, Thank you. :)
