### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by endel** [defold/tutorial-war-battles#4]
Hi there! 👋 

I'm considering revamping this tutorial on other platforms, and the lack of a license file got me wondering if I am allowed to do such a thing?

Does the source-code here have a different license than the assets?

Cheers!

**Comment by britzl** [comment]
The assets and source code are from https://github.com/defold/defold-examples and part of the license for Defold Additional Materials: https://defold.com/terms-and-conditions/#3-license-to-the-defold-additional-materials

**Comment by endel** [comment]
Awesome, thank you for clarifying @britzl, have a nice day! ❤️
